from common_variables import *
from app_variables import *
from data import *

MOBILE_SERVER = "{0}/mobile".format(SERVER)
MOBILE_CAREPASS_PATH = "https://{0}/".format(MOBILE_SERVER)

# MOBILE AUTH PAGES
MOBILE_LOGIN_URL = MOBILE_CAREPASS_PATH + 'login'
MOBILE_LOG_OUT = MOBILE_CAREPASS_PATH + 'logout'
MOBILE_REGISTRATION_URL = MOBILE_CAREPASS_PATH + 'register'

MOBILE_WELCOME_URL = MOBILE_CAREPASS_PATH + 'home'

# MOBILE APP MANAGEMENT PAGE
MOBILE_APP_URL = MOBILE_CAREPASS_PATH + 'apps'
MOBILE_APP_DETAIL = MOBILE_CAREPASS_PATH + 'app_detail/'        # https://qa2www.carepass.com/carepass/mobile/app_detail/fatsecret


# MOBILE USER PROFILE PAGE
MOBILE_BIOGRAPHY_URL = MOBILE_CAREPASS_PATH + 'myprofile'

# MOBILE GOAL URL
MOBILE_GET_STARTED_GOAL_URL = MOBILE_CAREPASS_PATH + 'goals'    # Goal selection page
MOBILE_GOAL_WIZARD_URL = MOBILE_CAREPASS_PATH + 'intro/'        # Goal Wizard

# Virtual Run or Walk 		1
# Fav Jeans 				2
# Kickstart Weight Loss 	4
# Custom goal 				9


# MOBILE PROFILES
MOBILE_FITNESS_PROFILE = MOBILE_CAREPASS_PATH + 'fitness'
MOBILE_NUTRITION_PROFILE = MOBILE_CAREPASS_PATH + 'nutrition'
MOBILE_DR_VISITS_PROFILE = MOBILE_CAREPASS_PATH + 'appointments'
MOBILE_INSURANCE_PROFILE = MOBILE_CAREPASS_PATH + 'insurance'
MOBILE_MOOD_PROFILE = MOBILE_CAREPASS_PATH + 'moods'
MOBILE_SLEEP_PROFILE = MOBILE_CAREPASS_PATH + 'sleep'
MOBILE_MEDICATIONS_PROFILE = MOBILE_CAREPASS_PATH + 'medications'
MOBILE_BODY_MEASUR_EMENT_PROFILE = MOBILE_CAREPASS_PATH + 'bodymeasurements'
MOBILE_LAB_RESULTS_PROFILE = MOBILE_CAREPASS_PATH + 'labresults'
MOBILE_CONDITIONS_PROFILE = MOBILE_CAREPASS_PATH + 'conditions'
MOBILE_LIFESTYLE_PROFILE = MOBILE_CAREPASS_PATH + 'lifestyle'

# STATIC PAGES
MOBILE_ITRIAGE_URL = MOBILE_CAREPASS_PATH + 'care'
MOBILE_HELP_URL = MOBILE_CAREPASS_PATH + 'help'
